## Merging the files with relations

In [1]:
import pandas as pd
import glob
import os
  
# merging the files
joined_files = os.path.join("/home/akumar/", "relations-*.csv")
  
# A list of all joined files is returned
joined_list = glob.glob(joined_files)
  
# Finally, the files are joined
df = pd.concat(map(pd.read_csv, joined_list), ignore_index=True)
df

,Unnamed: 0,relation,entity1,entity1_begin,entity1_end,chunk1,entity2,entity2_begin,entity2_end,chunk2,confidence
0,0,TrCP,PROBLEM,3816,3827,pneumothorax,TREATMENT,3839,3856,chest tube removal,0.906085
1,1,TrAP,PROBLEM,4939,4949,hypotensive,TREATMENT,4955,4966,the epidural,0.905324
2,2,TrAP,PROBLEM,4939,4949,hypotensive,TREATMENT,5003,5015,a fluid bolus,0.901337
3,3,TeRP,TEST,5193,5204,pan cultured,PROBLEM,5220,5227,organism,0.962884
4,4,TrAP,TREATMENT,5345,5357,Beta-blockers,PROBLEM,5376,5386,tachycardia,0.964870
...,...,...,...,...,...,...,...,...,...,...,...
953913,206760,TeCP,TEST,8852,8866,CTA of the neck,PROBLEM,8917,8937,thromboembolic source,0.997023
953914,206761,TeRP,TEST,8941,8943,CTA,PROBLEM,8979,8986,stenosis,0.997095
953915,206762,TeRP,TEST,8941,8943,CTA,PROBLEM,8991,9046,dissection throughout the vertebral and basila...,0.992096
953916,206763,TeRP,TEST,9401,9403,CTA,PROBLEM,9430,9439,dissection,0.916513
953917,206764,TeRP,TEST,9473,9476,Echo,PROBLEM,9491,9498,thrombus,0.996201

In [2]:
#saving as csv
df.to_csv("/home/akumar/merged_relations.csv")

In [2]:
#counting number of occurrences of each relation type
dict1={}
for val in df["relation"]:
    if val in dict1.keys():
        dict1[val]+=1
    else:
        dict1[val]=1
dict1

{'TrCP': 56432,
 'TrAP': 408080,
 'TeRP': 415883,
 'TeCP': 41109,
 'PIP': 12244,
 'TrIP': 13595,
 'TrNAP': 6306,
 'TrWP': 269}

### Updating type of relation based on links

In [3]:
df.loc[(df['relation'] == 'TrCP') & (df['entity1'] == 'PROBLEM'),'relation']= 'CAUSED BY'
df.loc[(df['relation'] == 'TrCP') & (df['entity1'] == 'TREATMENT'),'relation']= 'CAUSES PROBLEM'

df.loc[(df['relation'] == 'TrAP') & (df['entity1'] == 'PROBLEM'),'relation']= 'HAS TREATMENT'
df.loc[(df['relation'] == 'TrAP') & (df['entity1'] == 'TREATMENT'),'relation']= 'TREATS PROBLEM'

df.loc[(df['relation'] == 'TeRP') & (df['entity1'] == 'PROBLEM'),'relation']= 'DETECTED BY'
df.loc[(df['relation'] == 'TeRP') & (df['entity1'] == 'TEST'),'relation']= 'DETECTS'

df.loc[(df['relation'] == 'TeCP') & (df['entity1'] == 'PROBLEM'),'relation']= 'DETECTED BY'
df.loc[(df['relation'] == 'TeCP') & (df['entity1'] == 'TEST'),'relation']= 'DETECTS'

df.loc[(df['relation'] == 'TrIP') & (df['entity1'] == 'PROBLEM'),'relation']= 'CURED BY'
df.loc[(df['relation'] == 'TrIP') & (df['entity1'] == 'TREATMENT'),'relation']= 'CURES'

df.loc[(df['relation'] == 'TrNAP') & (df['entity1'] == 'PROBLEM'),'relation']= 'MUST AVOID'
df.loc[(df['relation'] == 'TrNAP') & (df['entity1'] == 'TREATMENT'),'relation']= 'AVOIDED FOR'

df.loc[(df['relation'] == 'TrWP') & (df['entity1'] == 'PROBLEM'),'relation']= 'WORSENED BY'
df.loc[(df['relation'] == 'TrWP') & (df['entity1'] == 'TREATMENT'),'relation']= 'WORSENS'

In [4]:
df

,Unnamed: 0,relation,entity1,entity1_begin,entity1_end,chunk1,entity2,entity2_begin,entity2_end,chunk2,confidence
0,0,CAUSED BY,PROBLEM,3816,3827,pneumothorax,TREATMENT,3839,3856,chest tube removal,0.906085
1,1,HAS TREATMENT,PROBLEM,4939,4949,hypotensive,TREATMENT,4955,4966,the epidural,0.905324
2,2,HAS TREATMENT,PROBLEM,4939,4949,hypotensive,TREATMENT,5003,5015,a fluid bolus,0.901337
3,3,DETECTS,TEST,5193,5204,pan cultured,PROBLEM,5220,5227,organism,0.962884
4,4,TREATS PROBLEM,TREATMENT,5345,5357,Beta-blockers,PROBLEM,5376,5386,tachycardia,0.964870
...,...,...,...,...,...,...,...,...,...,...,...
953913,206760,DETECTS,TEST,8852,8866,CTA of the neck,PROBLEM,8917,8937,thromboembolic source,0.997023
953914,206761,DETECTS,TEST,8941,8943,CTA,PROBLEM,8979,8986,stenosis,0.997095
953915,206762,DETECTS,TEST,8941,8943,CTA,PROBLEM,8991,9046,dissection throughout the vertebral and basila...,0.992096
953916,206763,DETECTS,TEST,9401,9403,CTA,PROBLEM,9430,9439,dissection,0.916513
953917,206764,DETECTS,TEST,9473,9476,Echo,PROBLEM,9491,9498,thrombus,0.996201

In [6]:
# df.to_csv("/home/akumar/updated_relations.csv")

In [5]:
values = ['TrCP','TrAP','TeRP','TeCP','TrIP','TrNAP','TrWP']

df_up = df[df.relation.isin(values) == False]

In [6]:
#dropping rows with null values
df_up.dropna(inplace=True)

<ipython-input-6-6db58a3df045>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_up.dropna(inplace=True)

In [7]:
df_up

,Unnamed: 0,relation,entity1,entity1_begin,entity1_end,chunk1,entity2,entity2_begin,entity2_end,chunk2,confidence
0,0,CAUSED BY,PROBLEM,3816,3827,pneumothorax,TREATMENT,3839,3856,chest tube removal,0.906085
1,1,HAS TREATMENT,PROBLEM,4939,4949,hypotensive,TREATMENT,4955,4966,the epidural,0.905324
2,2,HAS TREATMENT,PROBLEM,4939,4949,hypotensive,TREATMENT,5003,5015,a fluid bolus,0.901337
3,3,DETECTS,TEST,5193,5204,pan cultured,PROBLEM,5220,5227,organism,0.962884
4,4,TREATS PROBLEM,TREATMENT,5345,5357,Beta-blockers,PROBLEM,5376,5386,tachycardia,0.964870
...,...,...,...,...,...,...,...,...,...,...,...
953913,206760,DETECTS,TEST,8852,8866,CTA of the neck,PROBLEM,8917,8937,thromboembolic source,0.997023
953914,206761,DETECTS,TEST,8941,8943,CTA,PROBLEM,8979,8986,stenosis,0.997095
953915,206762,DETECTS,TEST,8941,8943,CTA,PROBLEM,8991,9046,dissection throughout the vertebral and basila...,0.992096
953916,206763,DETECTS,TEST,9401,9403,CTA,PROBLEM,9430,9439,dissection,0.916513
953917,206764,DETECTS,TEST,9473,9476,Echo,PROBLEM,9491,9498,thrombus,0.996201

In [8]:
#checking if null values still exist
df_up.isnull().values.any().sum()

0

### Removing duplicates

In [9]:
#making chunk1 lowercase
df_up["chunk1"] = df_up["chunk1"].str.lower()

<ipython-input-9-bb2a7346e363>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_up["chunk1"] = df_up["chunk1"].str.lower()

In [10]:
#making chunk2 lowercase
df_up["chunk2"] = df_up["chunk2"].str.lower()

<ipython-input-10-be08e09d565a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_up["chunk2"] = df_up["chunk2"].str.lower()

In [11]:
df_up

,Unnamed: 0,relation,entity1,entity1_begin,entity1_end,chunk1,entity2,entity2_begin,entity2_end,chunk2,confidence
0,0,CAUSED BY,PROBLEM,3816,3827,pneumothorax,TREATMENT,3839,3856,chest tube removal,0.906085
1,1,HAS TREATMENT,PROBLEM,4939,4949,hypotensive,TREATMENT,4955,4966,the epidural,0.905324
2,2,HAS TREATMENT,PROBLEM,4939,4949,hypotensive,TREATMENT,5003,5015,a fluid bolus,0.901337
3,3,DETECTS,TEST,5193,5204,pan cultured,PROBLEM,5220,5227,organism,0.962884
4,4,TREATS PROBLEM,TREATMENT,5345,5357,beta-blockers,PROBLEM,5376,5386,tachycardia,0.964870
...,...,...,...,...,...,...,...,...,...,...,...
953913,206760,DETECTS,TEST,8852,8866,cta of the neck,PROBLEM,8917,8937,thromboembolic source,0.997023
953914,206761,DETECTS,TEST,8941,8943,cta,PROBLEM,8979,8986,stenosis,0.997095
953915,206762,DETECTS,TEST,8941,8943,cta,PROBLEM,8991,9046,dissection throughout the vertebral and basila...,0.992096
953916,206763,DETECTS,TEST,9401,9403,cta,PROBLEM,9430,9439,dissection,0.916513
953917,206764,DETECTS,TEST,9473,9476,echo,PROBLEM,9491,9498,thrombus,0.996201

In [12]:
#remove duplicates
df_final = df_up.drop_duplicates(subset=['chunk1','chunk2'])

In [13]:
df_final

,Unnamed: 0,relation,entity1,entity1_begin,entity1_end,chunk1,entity2,entity2_begin,entity2_end,chunk2,confidence
0,0,CAUSED BY,PROBLEM,3816,3827,pneumothorax,TREATMENT,3839,3856,chest tube removal,0.906085
1,1,HAS TREATMENT,PROBLEM,4939,4949,hypotensive,TREATMENT,4955,4966,the epidural,0.905324
2,2,HAS TREATMENT,PROBLEM,4939,4949,hypotensive,TREATMENT,5003,5015,a fluid bolus,0.901337
3,3,DETECTS,TEST,5193,5204,pan cultured,PROBLEM,5220,5227,organism,0.962884
4,4,TREATS PROBLEM,TREATMENT,5345,5357,beta-blockers,PROBLEM,5376,5386,tachycardia,0.964870
...,...,...,...,...,...,...,...,...,...,...,...
953902,206749,DETECTED BY,PROBLEM,3420,3460,evolving bilateral pca territory infarcts,TEST,3481,3495,the prior study,0.993787
953903,206750,DETECTS,TEST,5635,5637,mri,PROBLEM,5678,5691,slow diffusion,0.997879
953904,206751,DETECTS,TEST,6739,6753,cta of the neck,PROBLEM,6804,6824,thromboembolic source,0.994271
953911,206758,DETECTS,TEST,8415,8424,repeat cxr,PROBLEM,8433,8443,opacity lll,0.997173
953915,206762,DETECTS,TEST,8941,8943,cta,PROBLEM,8991,9046,dissection throughout the vertebral and basila...,0.992096

In [14]:
df_final.to_csv("/home/akumar/final_relations.csv")

In [49]:
# for val in df_final2.duplicated(subset=['chunk1','chunk2']):
#     if val==True:
#         print('True')

### Data with Wikidata + MIMIC

In [1]:
#data with wikidata + MIMIC
import pandas as pd

data = pd.read_csv('medical_knowledge_base.csv')

### Removing duplicates as done above

In [2]:
data["chunk1"] = data["chunk1"].str.lower()

In [3]:
data["chunk2"] = data["chunk2"].str.lower()

In [4]:
data_final = data.drop_duplicates(subset=['chunk1','chunk2'])

In [5]:
data_final.isnull().values.any().sum()

0

In [6]:
data_final

,Unnamed: 0,relation,entity1,chunk1,entity2,chunk2
0,0,DETECTS,TEST,right upper quadrant ultrasound,PROBLEM,sludge in the gallbladder
1,1,CAUSED BY,PROBLEM,low calcium,TREATMENT,thyroid surgery
2,2,DETECTS,TEST,mri,PROBLEM,interval change
3,3,TREATS PROBLEM,TREATMENT,urgent hd,PROBLEM,your high potassium
4,4,HAS TREATMENT,PROBLEM,severe osa,TREATMENT,tracheostomy
...,...,...,...,...,...,...
608322,608322,TREATS PROBLEM,TREATMENT,hydral,PROBLEM,elevated bp
608323,608323,HAS TREATMENT,PROBLEM,afib/flutter,TREATMENT,rate controlled
608324,608324,HAS TREATMENT,PROBLEM,bladder prolapse,TREATMENT,repair
608325,608325,TREATS PROBLEM,TREATMENT,took motrin,PROBLEM,her throat irritation
608327,608327,DETECTS,TEST,ct chest with contrast,PROBLEM,scattered axillary lymph nodes

In [8]:
#final CSV file to be used to create the Knowledge Graph
data_final.to_csv("final_relations_wiki_mimic.csv")